from environs import Env

env = Env()
env.read_env()

BOT_TOKEN = env.str('BOT_TOKEN')
LOCATIONIQ_API_KEY = env.str('LOCATIONIQ_API_KEY')
LOCATIONIQ_BASE_URL = env.str('LOCATIONIQ_BASE_URL')
OPENWEATHER_API_KEY = env.str('OPENWEATHER_API_KEY')
OPENWEATHER_URL = env.str('OPENWEATHER_URL')
DEEPSEEK_TOKEN = env.str('DEEPSEEK_TOKEN')
DB_URL = env.str('DB_URL')
ADMINS = env.list('ADMINS')
PRIVATE_CHANNEL = env.str('PRIVATE_CHANNEL')
CHANNEL_USERNAME = env.str('CHANNEL_USERNAME')